services:

  api-consumo:

    build:
      context: .
      dockerfile: Dockerfile

    image: api-consumo:latest

    container_name: api-consumo

    restart: unless-stopped

    ports:
      - "127.0.0.1:8081:80"