server {

    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    index index.html;

    # Redireccionar la raiz
    location = / {
        return 302 /api-consumo/;
    }

    # Frontend React
    location /api-consumo/ {

        try_files $uri $uri/ /api-consumo/index.html;

    }

}